services:
  feedfactory:
    build: .
    container_name: feedfactory
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      #      - HF_TOKEN=${HF_TOKEN}
      #      - HF_SPACE=${HF_SPACE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - TZ=America/New_York
    volumes:
      - ./data:/app/data  # Persist the SQLite DB and XML files

  parser:
    image: tbelbek/postlight-readability-parser:latest
    expose:
      - "3000"
    restart: unless-stopped
